#!/usr/bin/env python3
"""Fix broken string escaping in 8 admin pages.
The fix_8_pages.py script generated Dart code with '${item[\'field\'] ?? \'\'}'
which is invalid — single quotes inside single-quoted string interpolation.
Fix: change to double-quoted strings: "${item['field'] ?? ''}"
"""
import os, re

PAGES_DIR = "/home/z/my-project/virent-dart/mobile/lib/features/admin_web/pages"

# 8 files generated by fix_8_pages.py
FILES = [
    'tariffs_page.dart',
    'tariff_subtariffs_page.dart',
    'tariffs_subscriptions_page.dart',
    'task_technicians_page.dart',
    'settings_drivers_page.dart',
    'settings_scooter_groups_page.dart',
    'sms_logs_page.dart',
    'iot_page.dart',
]

fixes = 0
for fn in FILES:
    fp = os.path.join(PAGES_DIR, fn)
    with open(fp) as f: c = f.read()
    orig = c
    
    # Fix pattern: '${item[\'field\'] ?? \'\'}' -> "${item['field'] ?? ''}"
    # The broken pattern uses \' inside single-quoted string
    c = re.sub(
        r"'\$\{item\[\\'(\w+)\\'\] \?\? \\''\}'",
        r'${"\${item[\'\1\'] ?? \'\'}"}',
        c
    )
    
    # Simpler approach: just replace the whole broken pattern
    # Pattern: '${item[\'FIELD\'] ?? \'\'}'
    # Replace with: "${item['FIELD'] ?? ''}"
    def fix_initial(m):
        field = m.group(1)
        return '"${item[\'%s\'] ?? \'\'}"' % field
    
    c = re.sub(
        r"'\$\{item\[\\'([^']+)\\'\] \?\? \\''\}'",
        fix_initial,
        c
    )
    
    if c != orig:
        with open(fp, 'w') as f: f.write(c)
        fixes += 1
        print(f"Fixed: {fn}")

print(f"\n=== {fixes} files fixed ===")
